services:
  - type: web
    name: opsdesk-api
    runtime: docker
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MINUTES
        value: "120"
